


%% GENERAL PRBS
clear all
close all
clc

data_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/data';
fig_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/fig/';

% Change to data directory
cd(data_dir);
cd('flight_test_inputs');
load 63.csv
u1 = X63(:,1);
clear X63

h = figure(1);
x = 1:30;
y = u1(15:44);
s = stairs(x,y);
Xlabel = xlabel('t');
axis([1 30 -1.2 1.2])

set( s,...
    'LineWidth'   , 1.25, ...
    'color'       , [.1 .1 .1]);

set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'XTickLabel'  ,  [], ...
    'YTickLabel'  ,  {'-b', ' ', 'b'}, ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 9, ...
    'yGrid'       , 'on', ...
    'xTick'       , [1:1:30], ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);



set([Xlabel], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);

cd(fig_dir);
set(gcf,'PaperUnits','inches','PaperPosition',[0 0 6.5 1.25])
print(h, '-depsc2', 'general_prbs.eps', '-r100')
close(gcf);

%% TEST PRBS
clear all
close all
clc

max_pitch = 10;
max_roll = 10;
max_yaw = 50;


data_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/data';
fig_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/fig/';


cd(data_dir);
cd('flight_test_inputs');
load 63.csv
u1 = X63(:,1);
u2 = X63(:,2);
u3 = X63(:,3);
clear X63

u_size = size(u1);
len = u_size(1);
x = 15:len;
u1 = u1(15:end).*max_pitch;
u2 = u2(15:end).*max_roll;
u3 = u3(15:end).*max_yaw;

h = figure(1);

subplot(3,1,1)
s1 = stairs(x,u1);
Ylabel = ylabel({'pitch, u_1';'(deg/s)'});
axis([15 len -1.2*max_pitch 1.2*max_pitch])
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'YTickLabel'  ,  {-1*max_pitch, ' ', max_pitch}, ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 9, ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);
set([Ylabel], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);

subplot(3,1,2)
s2 = stairs(x,u2);
Ylabel = ylabel({'roll, u_2';'(deg/s)'});
axis([15 len -1.2*max_roll 1.2*max_roll])
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'YTickLabel'  ,  {-1*max_roll, ' ', max_roll}, ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 9, ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);
set([Ylabel], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);

subplot(3,1,3)
s3 = stairs(x,u3);
Xlabel = xlabel('k');
Ylabel = ylabel({'yaw rate, u_3';'(deg/s^2)'});
axis([15 len -1.2*max_yaw 1.2*max_yaw])
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'YTickLabel'  ,  {-1*max_yaw, ' ', max_yaw}, ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 9, ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);
set([Xlabel Ylabel], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);

set( [s1 s2 s3],...
    'LineWidth'   , 1.25, ...
    'color'       , [.1 .1 .1]);

cd(fig_dir);
set(gcf,'PaperUnits','inches','PaperPosition',[0 0 6 4])
print(h, '-depsc2', 'test_prbs.eps', '-r100')
close(gcf);