clear all
close all
clc

ts = 1/50;

model = '1760';
shift = [-0.6 0.3 1.45 1650 0 -210];
front_trim = 1;

fig_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/fig/';
fig_name = 'sim_1760_pitch.eps';

% Load model
model_path = '/Users/akee/School/UCLA/01 thesis/uclathesis/data/models/20131017212836_63_39500/';
model_file = strcat('parsim_',model, '_8.mat');
load(strcat(model_path, model_file))

% set initial condition
sys.ts = 1/50;


% Load verification data
ver_path = '/Users/akee/School/UCLA/01 thesis/uclathesis/data/verification/';
ver_file = '20131126163250_pitch_41000/20131126163250_pitch_41000.mat';
load(strcat(ver_path, ver_file));
u_ver = u;
y_ver = y;
clear u y

% build iddata object and estimate states
ver_dat = iddata(y_ver,u_ver,ts);
x0est = findstates(sys,ver_dat);

y_sim = sim(sys,ver_dat.u);
%y_sim = sim(sys,ver_dat.u, 'InitialCondition',x0est);

y_sim(:,1) = y_sim(:,1) + shift(1);
y_sim(:,2) = y_sim(:,2) + shift(2);
y_sim(:,3) = y_sim(:,3) + shift(3);
y_sim(:,4) = y_sim(:,4) + shift(4);

y_sim(:,6) = y_sim(:,6) + shift(6);

y_sim(:,5) = detrend(y_sim(:,5), 'linear', 90);
y_sim(:,5) = y_sim(:,5) + shift(5);

y_ver(:,6) = detrend(y_ver(:,6), 'linear', 80);

[Len dim] = size(u_ver);
X = 1:Len;
t = X.*ts;


h = figure(1);
subplot(6,1,4)
plot(t, y_ver(:,1), 'k-')
hold on
plot(t, y_sim(:,1), 'k--')
axis([1 2.5 -0.5 0.5])
y1 = ylabel('acc x');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

subplot(6,1,5)
plot(t, y_ver(:,2), 'k-')
hold on
plot(t, y_sim(:,2), 'k--')
axis([1 2.5 -0.5 0.5])
y2 = ylabel('acc y');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

subplot(6,1,6)
plot(t, y_ver(:,3), 'k-')
hold on
plot(t, y_sim(:,3), 'k--')
axis([1 2.5 0 2])
y3 = ylabel('acc z');
x = xlabel('Time (sec.)');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

subplot(6,1,1)
plot(t, y_ver(:,4), 'k-')
hold on
plot(t, y_sim(:,4), 'k--')
axis([1 2.5 -250 250])
y4 = ylabel('gyro x');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

subplot(6,1,2)
plot(t, y_ver(:,5), 'k-')
hold on
plot(t, y_sim(:,5), 'k--')
axis([1 2.5 -500 500])
y5 = ylabel('gyro y');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

subplot(6,1,3)
plot(t, y_ver(:,6), 'k-')
hold on
plot(t, y_sim(:,6), 'k--')
axis([1 2.5 -50 50])
y6 = ylabel('gyro z');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2]);

set([x, y1, y2, y3, y4, y5, y6], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);

set(gcf,'PaperUnits','inches','PaperPosition',[0 0 6.5 8])
out_file = strcat(fig_dir, fig_name);
print(h, '-depsc2', out_file, '-r100')
close(gcf);