%Step response

clear all
close all
clc

linewidth = 1.5;

ts = 1/50;
fig_dir = '/Users/akee/School/UCLA/01 thesis/uclathesis/fig/';
fig_name = 'step_resp_parsim.eps';

% Load model
load('/Users/akee/School/UCLA/01 thesis/uclathesis/data/models/20131017212836_63_39500/parsim_1663_8.mat');

% set initial condition
sys.ts = 1/50;


t = [-.2:.02:0.8];
st = step(sys,t);
u1y1 = st(:,1,1);
u1y2 = st(:,2,1);
u1y3 = st(:,3,1);
u1y4 = st(:,4,1);
u1y5 = st(:,5,1);
u1y6 = st(:,6,1);
u2y1 = st(:,1,2);
u2y2 = st(:,2,2);
u2y3 = st(:,3,2);
u2y4 = st(:,4,2);
u2y5 = st(:,5,2);
u2y6 = st(:,6,2);
u3y1 = st(:,1,3);
u3y2 = st(:,2,3);
u3y3 = st(:,3,3);
u3y4 = st(:,4,3);
u3y5 = st(:,5,3);
u3y6 = st(:,6,3);
u4y1 = st(:,1,4);
u4y2 = st(:,2,4);
u4y3 = st(:,3,4);
u4y4 = st(:,4,4);
u4y5 = st(:,5,4);
u4y6 = st(:,6,4);

h = figure(1);
subplot(6,4,1)
plot(t,u1y1, 'k-', 'LineWidth', linewidth)
t1 = title({'From u_1';' '}, 'Color', [.2 .2 .2]);
x1 = xlabel('Time');
y1 = ylabel('To  y_1');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,2)
plot(t,u2y1, 'k-', 'LineWidth', linewidth)
t2 = title({'From u_2';' '}, 'Color', [.2 .2 .2]);
x2 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,3)
plot(t,u3y1, 'k-', 'LineWidth', linewidth)
t3 = title({'From u_3';' '}, 'Color', [.2 .2 .2]);
x3 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,4)
plot(t,u4y1, 'k-', 'LineWidth', linewidth)
t4 = title({'From u_4';' '});
x4 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,5)
plot(t,u1y2, 'k-', 'LineWidth', linewidth)
y5 = ylabel('To  y_2');
x5 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,6)
plot(t,u2y2, 'k-', 'LineWidth', linewidth)
x6 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,7)
plot(t,u3y2, 'k-', 'LineWidth', linewidth)
x7 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,8)
plot(t,u4y2, 'k-', 'LineWidth', linewidth)
x8 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-2.5*10^-6 2.5*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,9)
plot(t,u1y3, 'k-', 'LineWidth', linewidth)
y9 = ylabel('To  y_3');
x9 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-6*10^-6 6*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,10)
plot(t,u2y3, 'k-', 'LineWidth', linewidth)
x10 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-6*10^-6 6*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,11)
plot(t,u3y3, 'k-', 'LineWidth', linewidth)
x11 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-6*10^-6 6*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,12)
plot(t,u4y3, 'k-', 'LineWidth', linewidth)
x12 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-6*10^-6 6*10^-6], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,13)
plot(t,u1y4, 'k-', 'LineWidth', linewidth)
y13 = ylabel('To  y_4');
x13 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-3 8*10^-3], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,14)
plot(t,u2y4, 'k-', 'LineWidth', linewidth)
x14 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-3 8*10^-3], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,15)
plot(t,u3y4, 'k-', 'LineWidth', linewidth)
x15 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-3 8*10^-3], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,16)
plot(t,u4y4, 'k-', 'LineWidth', linewidth)
x16 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-3 8*10^-3], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,17)
plot(t,u1y5, 'k-', 'LineWidth', linewidth)
y17 = ylabel('To  y_5');
x17 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-1*10^-2 1.5*10^-2], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,18)
plot(t,u2y5, 'k-', 'LineWidth', linewidth)
x18 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-1*10^-2 1.5*10^-2], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,19)
plot(t,u3y5, 'k-', 'LineWidth', linewidth)
x19 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-1*10^-2 1.5*10^-2], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,20)
plot(t,u4y5, 'k-', 'LineWidth', linewidth)
x20 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-1*10^-2 1.5*10^-2], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,21)
plot(t,u1y6, 'k-', 'LineWidth', linewidth)
y21 = ylabel('To  y_6');
x21 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-4 8*10^-4], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,22)
plot(t,u2y6, 'k-', 'LineWidth', linewidth)
x22 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-4 8*10^-4], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,23)
plot(t,u3y6, 'k-', 'LineWidth', linewidth)
x23 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-4 8*10^-4], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});


subplot(6,4,24)
plot(t,u4y6, 'k-', 'LineWidth', linewidth)
x24 = xlabel('Time');
set( gca,...
    'box'         , 'off', ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.015 .015] , ...
    'FontName'    , 'AvantGarde', ...
    'FontSize'    , 8, ...
    'xGrid'       , 'on', ...
    'yGrid'       , 'on', ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'Xlim'        , [-0.2 0.81], ...
    'Ylim'        , [-8*10^-4 8*10^-4], ...
    'XTicklabel'  , {'','0.0','0.2','0.4','0.6','0.8'});




set([x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, ...
     t1, t2, t3, t4, y1, y5, y9, y13, y17, y21], ...
    'FontName'    , 'AvantGarde', ...
    'FontWeight'  , 'bold', ...
    'FontSize'    , 9);


set(gcf,'PaperUnits','inches','PaperPosition',[0 0 6.5 8])
out_file = strcat(fig_dir, fig_name);
print(h, '-depsc2', out_file, '-r100')
close(gcf);